person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12

#profiles 指定两个环境端口配置 使用active激活指定环境
spring:
  profiles:
    active: prd
---
server:
  port: 8080
spring:
  profiles: dev

---
server:
  port: 9090
spring:
  profiles: prd